### ISSUE TITLE
Forum migration tracking issue

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#62]
[WIP]

Forum needs to move from `trident` to `tribune`, encompassing both our own tweaks & other changes to prepare for an upgrade to PHP 7.4 then PHP 8.0 in early summer. This is a tracking issue for tasks involved since it's not trivial.

### Sandbox

- [x] set up sandbox subdomain on `tribune` (@petecoper)
- [x] get migration snapshot of files + db from `trident` (@petecoper)
- [x] reconfigure snapshot for sandbox domain on `tribune`  (@petecoper)
- [x] apply modifications and benchmark database upgrade process on `tribune` (perhaps off peak if intensive action) (@philwareham)
- [x] sanity check front- and admin-side for any snagging on `tribune`  (@philwareham)
- [x] sign off sandboxing process (@philwareham)

### Preflight

- [x] decide schedule for migration (@petecooper & @philwareham)
- [x] communicate to forum & socials (@petecooper or @philwareham)
- [x] set forum `A` and `AAAA` records to minimum TTL (@petecooper or @philwareham)

### Launch

- [x] check full backup from `trident` schedule (@petecooper)
- [x] set forum on `trident` to maintenance mode (@petecooper)
- [x] full backup locally (@petecooper)
- [x] repoint DNS to `tribune` (@petecooper)
- [x] get new TLS (@petecooper)
- [x] restore backup to `tribune` (@petecooper)
- [x] create, run and check full backup from `tribune` (@petecooper)
- [x] run database upgrade script(s) (@philwareham)
- [x] run and check full backup from `tribune` (@petecooper)
- [x] disable maintenance mode on `tribune` (@petecooper or @philwareham)
- [x] communicate to forum & socials (@petecooper or @philwareham)

#### Day of

- [ ] monitor resource usage (@petecooper)
- [ ] monitor socials (@petecooper or @philwareham)

#### +3 days

- [ ] get archive snapshot of final `trident`  (@petecooper)
- [ ] tidy up test forum remnants (files, DNS etc)   (@petecooper)

**Comment by philwareham** [comment]
Looks like a plan. Shout when ready for my tasks.

**Comment by petecooper** [comment]
I'm still getting a brick wall when moving to another domain, so I need to investigate why that's happening. Will be in touch.

**Comment by petecooper** [comment]
We're good. Closing.
